### ISSUE TITLE
add: Vue 3's JSX

### ISSUE THREAD

**Issue by icarusgk** [sonikjs/sonik#11]
Hello Sonik team! 💚

In Vue you can also use JSX: https://vuejs.org/guide/extras/render-function.html#jsx-tsx
Maybe you could include Vue into **Sonik** as well, it'd be a great addition to the JSX-based framework list. Thank you! <3

**Comment by yusukebe** [comment]
Thanks for the good suggestion, but please wait a bit for Sonik as the API will be changed later.

**Comment by icarusgk** [comment]
Great!, thank you for considering it. 😄
